import type { MediaContext } from '../api/media-context.js';
import * as ME from '../api/media-events.js';
import { MediaPlayerController } from '../api/player-controller.js';
import type { MediaRequestContext } from './media-request-manager.js';
/**
 * This class is responsible for listening to and normalizing media events, updating the media
 * state context, and satisfying media requests.
 */
export declare class MediaStateManager extends MediaPlayerController {
    private _request;
    private _media;
    private readonly _trackedEvents;
    private _clipEnded;
    private _firingWaiting;
    private _waitingTrigger;
    constructor(_request: MediaRequestContext, _media: MediaContext);
    protected onAttach(el: HTMLElement): void;
    protected onConnect(el: HTMLElement): void;
    protected onDestroy(): void;
    _handle(event: Event): void;
    private _isPlayingOnDisconnect;
    private _resumePlaybackOnConnect;
    private _pausePlaybackOnDisconnect;
    private _resetTracking;
    private _satisfyRequest;
    private _addTextTrackListeners;
    private _addQualityListeners;
    private _addAudioTrackListeners;
    private _onTextTracksChange;
    private _onTextTrackModeChange;
    private _onAudioTracksChange;
    private _onAudioTrackChange;
    private _onQualitiesChange;
    private _onQualityChange;
    private _onAutoQualityChange;
    private _stopQualityResizeEffect;
    private _watchQualityResize;
    private _stopWatchingQualityResize;
    private _onCanSetQualityChange;
    protected _watchCanSetVolume(): void;
    ['provider-change'](event: ME.MediaProviderChangeEvent): void;
    ['provider-loader-change'](event: ME.MediaProviderLoaderChangeEvent): void;
    ['auto-play'](event: ME.MediaAutoPlayEvent): void;
    ['auto-play-fail'](event: ME.MediaAutoPlayFailEvent): void;
    ['can-load'](event: ME.MediaCanLoadEvent): void;
    ['can-load-poster'](event: ME.MediaCanLoadEvent): void;
    ['media-type-change'](event: ME.MediaTypeChangeEvent): void;
    ['stream-type-change'](event: ME.MediaStreamTypeChangeEvent): void;
    ['rate-change'](event: ME.MediaRateChangeEvent): void;
    ['remote-playback-change'](event: ME.MediaRemotePlaybackChangeEvent): void;
    ['sources-change'](event: ME.MediaSourcesChangeEvent): void;
    private _onSourceQualitiesChange;
    ['source-change'](event: ME.MediaSourceChangeEvent): void;
    private _resetMediaState;
    ['abort'](event: ME.MediaAbortEvent): void;
    ['load-start'](event: ME.MediaLoadStartEvent): void;
    ['error'](event: ME.MediaErrorEvent): void;
    ['loaded-metadata'](event: ME.MediaLoadedMetadataEvent): void;
    ['loaded-data'](event: ME.MediaLoadedDataEvent): void;
    ['can-play'](event: ME.MediaCanPlayEvent): void;
    ['can-play-through'](event: ME.MediaCanPlayThroughEvent): void;
    protected _onCanPlayDetail(detail: ME.MediaCanPlayDetail): void;
    ['duration-change'](event: ME.MediaDurationChangeEvent): void;
    ['progress'](event: ME.MediaProgressEvent): void;
    ['play'](event: ME.MediaPlayEvent): void;
    private _resetPlaybackIfNeeded;
    ['play-fail'](event: ME.MediaPlayFailEvent): void;
    ['playing'](event: ME.MediaPlayingEvent): void;
    ['started'](event: Event): void;
    ['pause'](event: ME.MediaPauseEvent): void;
    ['time-update'](event: ME.MediaTimeUpdateEvent): void;
    private _onEndPrecisionChange;
    private _saveTime;
    ['audio-gain-change'](event: ME.MediaAudioGainChangeEvent): void;
    ['volume-change'](event: ME.MediaVolumeChangeEvent): void;
    ['seeking']: ((event: ME.MediaSeekingEvent) => void) & {
        cancel: () => void;
        flush: () => void;
    };
    ['seeked'](event: ME.MediaSeekedEvent): void;
    ['waiting'](event: ME.MediaWaitingEvent): void;
    private _fireWaiting;
    ['end'](event: Event): void;
    private _onEnded;
    private _stopWaiting;
    ['fullscreen-change'](event: ME.MediaFullscreenChangeEvent): void;
    ['fullscreen-error'](event: ME.MediaFullscreenErrorEvent): void;
    ['orientation-change'](event: ME.MediaOrientationChangeEvent): void;
    ['picture-in-picture-change'](event: ME.MediaPIPChangeEvent): void;
    ['picture-in-picture-error'](event: ME.MediaPIPErrorEvent): void;
    ['title-change'](event: ME.MediaPosterChangeEvent): void;
    ['poster-change'](event: ME.MediaPosterChangeEvent): void;
}
