import { d as defineCustomElement } from '../chunks/vidstack-CBNXqr3M.js';
import { h as MediaPlayButtonElement, f as MediaMuteButtonElement, c as MediaCaptionButtonElement, g as MediaPIPButtonElement, d as MediaFullscreenButtonElement, i as MediaSeekButtonElement, b as MediaAirPlayButtonElement, e as MediaLiveButtonElement, v as MediaVolumeSliderElement, t as MediaTimeSliderElement, u as MediaSliderPreviewElement, r as MediaSliderThumbnailElement, s as MediaSliderValueElement, l as MediaMenuElement, m as MediaMenuButtonElement, o as MediaMenuItemsElement, n as MediaMenuItemElement, j as MediaAudioRadioGroupElement, k as MediaCaptionsRadioGroupElement, p as MediaSpeedRadioGroupElement, q as MediaQualityRadioGroupElement, a as MediaTimeElement, M as MediaThumbnailElement } from '../chunks/vidstack-CtdwOTCT.js';
import { MediaPlyrLayoutElement } from './plyr-layout-el.js';
import { MediaPosterElement } from '../chunks/vidstack-BuXAfxgW.js';
import '../chunks/vidstack-Dv7HWUBr.js';
import '../chunks/vidstack-DopyK5ml.js';
import '../chunks/vidstack-VrKElWm_.js';
import '../chunks/vidstack-DlGT_9qi.js';
import '../chunks/vidstack-C5IKOUzO.js';
import '../chunks/vidstack-THZVvA_p.js';
import '../chunks/vidstack-BTmcG2zk.js';
import '../chunks/vidstack-DoOTQiYD.js';
import '../chunks/vidstack-BSXZsAhp.js';
import '../chunks/vidstack-BUqeBbTQ.js';
import '../chunks/vidstack-ksPACRiU.js';
import '../chunks/vidstack-CSaHpIQV.js';
import '../chunks/vidstack-DuqfpSxk.js';
import '../chunks/vidstack-CysHdt3L.js';
import '../chunks/vidstack-Bf6opHxk.js';
import '../chunks/vidstack-_f_0FzgB.js';
import '../chunks/vidstack-rsZGrNIW.js';

defineCustomElement(MediaPlyrLayoutElement);
defineCustomElement(MediaPosterElement);
defineCustomElement(MediaPlayButtonElement);
defineCustomElement(MediaMuteButtonElement);
defineCustomElement(MediaCaptionButtonElement);
defineCustomElement(MediaPIPButtonElement);
defineCustomElement(MediaFullscreenButtonElement);
defineCustomElement(MediaSeekButtonElement);
defineCustomElement(MediaAirPlayButtonElement);
defineCustomElement(MediaLiveButtonElement);
defineCustomElement(MediaVolumeSliderElement);
defineCustomElement(MediaTimeSliderElement);
defineCustomElement(MediaSliderPreviewElement);
defineCustomElement(MediaSliderThumbnailElement);
defineCustomElement(MediaSliderValueElement);
defineCustomElement(MediaMenuElement);
defineCustomElement(MediaMenuButtonElement);
defineCustomElement(MediaMenuItemsElement);
defineCustomElement(MediaMenuItemElement);
defineCustomElement(MediaAudioRadioGroupElement);
defineCustomElement(MediaCaptionsRadioGroupElement);
defineCustomElement(MediaSpeedRadioGroupElement);
defineCustomElement(MediaQualityRadioGroupElement);
defineCustomElement(MediaTimeElement);
defineCustomElement(MediaThumbnailElement);
