import { d as defineCustomElement } from '../chunks/vidstack-ND4uzLKO.js';
import { h as MediaPlayButtonElement, f as MediaMuteButtonElement, c as MediaCaptionButtonElement, g as MediaPIPButtonElement, d as MediaFullscreenButtonElement, i as MediaSeekButtonElement, b as MediaAirPlayButtonElement, e as MediaLiveButtonElement, v as MediaVolumeSliderElement, t as MediaTimeSliderElement, u as MediaSliderPreviewElement, r as MediaSliderThumbnailElement, s as MediaSliderValueElement, l as MediaMenuElement, m as MediaMenuButtonElement, o as MediaMenuItemsElement, n as MediaMenuItemElement, j as MediaAudioRadioGroupElement, k as MediaCaptionsRadioGroupElement, p as MediaSpeedRadioGroupElement, q as MediaQualityRadioGroupElement, a as MediaTimeElement, M as MediaThumbnailElement } from '../chunks/vidstack-CiJ6cioV.js';
import { MediaPlyrLayoutElement } from './plyr-layout-el.js';
import { MediaPosterElement } from '../chunks/vidstack-Sx7aEl95.js';
import '../chunks/vidstack-Ga5LXVQf.js';
import '../chunks/vidstack-BmzHu3v_.js';
import '../chunks/vidstack-CnaYRoc3.js';
import '../chunks/vidstack-Ca9dj_1Q.js';
import '../chunks/vidstack-BNJih9gD.js';
import '../chunks/vidstack-DpIrri-f.js';
import '../chunks/vidstack-CkfyfBu0.js';
import '../chunks/vidstack-BuYg7N1V.js';
import '../chunks/vidstack-1gmLGa6x.js';
import '../chunks/vidstack-DM_McBs5.js';
import '../chunks/vidstack-ksPACRiU.js';
import '../chunks/vidstack-CSaHpIQV.js';
import '../chunks/vidstack-pWEcRV_H.js';
import '../chunks/vidstack-DDJ8xFNz.js';
import '../chunks/vidstack-Nzpo6ock.js';
import '../chunks/vidstack-m43RuAVk.js';
import '../chunks/vidstack-Do6-rxiG.js';

defineCustomElement(MediaPlyrLayoutElement);
defineCustomElement(MediaPosterElement);
defineCustomElement(MediaPlayButtonElement);
defineCustomElement(MediaMuteButtonElement);
defineCustomElement(MediaCaptionButtonElement);
defineCustomElement(MediaPIPButtonElement);
defineCustomElement(MediaFullscreenButtonElement);
defineCustomElement(MediaSeekButtonElement);
defineCustomElement(MediaAirPlayButtonElement);
defineCustomElement(MediaLiveButtonElement);
defineCustomElement(MediaVolumeSliderElement);
defineCustomElement(MediaTimeSliderElement);
defineCustomElement(MediaSliderPreviewElement);
defineCustomElement(MediaSliderThumbnailElement);
defineCustomElement(MediaSliderValueElement);
defineCustomElement(MediaMenuElement);
defineCustomElement(MediaMenuButtonElement);
defineCustomElement(MediaMenuItemsElement);
defineCustomElement(MediaMenuItemElement);
defineCustomElement(MediaAudioRadioGroupElement);
defineCustomElement(MediaCaptionsRadioGroupElement);
defineCustomElement(MediaSpeedRadioGroupElement);
defineCustomElement(MediaQualityRadioGroupElement);
defineCustomElement(MediaTimeElement);
defineCustomElement(MediaThumbnailElement);
