// TODO : add rtl
// https://github.com/annexare/Countries/blob/main/packages/countries/src/data/languages.ts

export const languages = [
  { code: "af", nativeName: "Afrikaans", flag: "🇿🇦", name: "Afrikaans" },
  { code: "sq", nativeName: "Shqip", flag: "🇦🇱", name: "Albanian" },
  { code: "am", nativeName: "አማርኛ", flag: "🇪🇹", name: "Amharic" },
  {
    code: "en-AU",
    nativeName: "English (Australia)",
    flag: "🇦🇺",
    name: "English",
  },
  {
    code: "en-CA",
    nativeName: "English (Canada)",
    flag: "🇨🇦",
    name: "English",
  },
  {
    code: "en-GB",
    nativeName: "English (United Kingdom)",
    flag: "🇬🇧",
    name: "English",
  },
  { code: "en", nativeName: "English", flag: "🇺🇸", name: "English" },
  { code: "ar", nativeName: "العربية", flag: "🇸🇦", name: "Arabic" },
  { code: "hy", nativeName: "Հայերեն", flag: "🇦🇲", name: "Armenian" },
  { code: "my", nativeName: "ဗမာ", flag: "🇲🇲", name: "Burmese" },
  { code: "eu", nativeName: "Euskara", flag: "🇪🇸", name: "Basque" },
  { code: "bn", nativeName: "বাংলা", flag: "🇧🇩", name: "Bengali" },
  { code: "bg", nativeName: "Български", flag: "🇧🇬", name: "Bulgarian" },
  { code: "be", nativeName: "Беларуская", flag: "🇧🇾", name: "Belarusian" },
  { code: "hr", nativeName: "Hrvatski", flag: "🇭🇷", name: "Croatian" },
  { code: "da", nativeName: "Dansk", flag: "🇩🇰", name: "Danish" },
  { code: "et", nativeName: "Eesti", flag: "🇪🇪", name: "Estonian" },
  { code: "tl", nativeName: "Filipino", flag: "🇵🇭", name: "Filipino" },
  { code: "fi", nativeName: "Suomi", flag: "🇫🇮", name: "Finnish" },
  {
    code: "fr-FR",
    nativeName: "Français (France)",
    flag: "🇫🇷",
    name: "French",
  },
  {
    code: "fr-CA",
    nativeName: "Français (Canada)",
    flag: "🇨🇦",
    name: "French",
  },
  { code: "gl", nativeName: "Galego", flag: "🇪🇸", name: "Galician" },
  { code: "ka", nativeName: "ქართული", flag: "🇬🇪", name: "Georgian" },
  { code: "gu", nativeName: "ગુજરાતી", flag: "🇮🇳", name: "Gujarati" },
  { code: "he", nativeName: "עברית", flag: "🇮🇱", name: "Hebrew" },
  { code: "hi", nativeName: "हिन्दी", flag: "🇮🇳", name: "Hindi" },
  { code: "id", nativeName: "Indonesia", flag: "🇮🇩", name: "Indonesian" },
  { code: "is", nativeName: "Íslenska", flag: "🇮🇸", name: "Icelandic" },
  { code: "it", nativeName: "Italiano", flag: "🇮🇹", name: "Italian" },
  { code: "ja", nativeName: "日本語", flag: "🇯🇵", name: "Japanese" },
  { code: "kn", nativeName: "ಕನ್ನಡ", flag: "🇮🇳", name: "Kannada" },
  { code: "ca", nativeName: "Català", flag: "🇪🇸", name: "Catalan" },
  { code: "kk", nativeName: "Қазақ тілі", flag: "🇰🇿", name: "Kazakh" },
  { code: "km", nativeName: "ខ្មែរ", flag: "🇰🇭", name: "Khmer" },
  { code: "ko", nativeName: "한국어", flag: "🇰🇷", name: "Korean" },
  { code: "ky", nativeName: "Кыргызча", flag: "🇰🇬", name: "Kyrgyz" },
  { code: "lo", nativeName: "ລາວ", flag: "🇱🇦", name: "Lao" },
  { code: "lt", nativeName: "Lietuvių", flag: "🇱🇹", name: "Lithuanian" },
  { code: "lv", nativeName: "Latviešu", flag: "🇱🇻", name: "Latvian" },
  { code: "mk", nativeName: "Македонски", flag: "🇲🇰", name: "Macedonian" },
  { code: "ml", nativeName: "മലയാളം", flag: "🇮🇳", name: "Malayalam" },
  {
    code: "ms-MY",
    nativeName: "Bahasa Melayu (Malaysia)",
    flag: "🇲🇾",
    name: "Malay (Malaysia)",
  },
  { code: "ms", nativeName: "Bahasa Melayu", flag: "🇲🇾", name: "Malay" },
  { code: "mr", nativeName: "मराठी", flag: "🇮🇳", name: "Marathi" },
  { code: "hu", nativeName: "Magyar", flag: "🇭🇺", name: "Hungarian" },
  { code: "mn", nativeName: "Монгол", flag: "🇲🇳", name: "Mongolian" },
  { code: "ne", nativeName: "नेपाली", flag: "🇳🇵", name: "Nepali" },
  { code: "nl", nativeName: "Nederlands", flag: "🇳🇱", name: "Dutch" },
  { code: "no", nativeName: "Norsk", flag: "🇳🇴", name: "Norwegian" },
  { code: "de", nativeName: "Deutsch", flag: "🇩🇪", name: "German" },
  { code: "pa", nativeName: "ਪੰਜਾਬੀ", flag: "🇮🇳", name: "Punjabi" },
  { code: "fa", nativeName: "فارسی", flag: "🇮🇷", name: "Persian" },
  { code: "pl", nativeName: "Polski", flag: "🇵🇱", name: "Polish" },
  {
    code: "pt-BR",
    nativeName: "Português (Brasil)",
    flag: "🇧🇷",
    name: "Portuguese (Brazil)",
  },
  {
    code: "pt-PT",
    nativeName: "Português (Portugal)",
    flag: "🇵🇹",
    name: "Portuguese (Portugal)",
  },
  { code: "ro", nativeName: "Română", flag: "🇷🇴", name: "Romanian" },
  { code: "ru", nativeName: "Русский", flag: "🇷🇺", name: "Russian" },
  { code: "rm", nativeName: "Rumantsch", flag: "🇨🇭", name: "Romansh" },
  { code: "si", nativeName: "සිංහල", flag: "🇱🇰", name: "Sinhala" },
  { code: "sk", nativeName: "Slovenčina", flag: "🇸🇰", name: "Slovak" },
  { code: "sl", nativeName: "Slovenščina", flag: "🇸🇮", name: "Slovenian" },
  { code: "sr", nativeName: "Српски", flag: "🇷🇸", name: "Serbian" },
  { code: "sw", nativeName: "Kiswahili", flag: "🇹🇿", name: "Swahili" },
  { code: "ta", nativeName: "தமிழ்", flag: "🇮🇳", name: "Tamil" },
  { code: "te", nativeName: "తెలుగు", flag: "🇮🇳", name: "Telugu" },
  { code: "th", nativeName: "ไทย", flag: "🇹🇭", name: "Thai" },
  { code: "tr", nativeName: "Türkçe", flag: "🇹🇷", name: "Turkish" },
  { code: "uk", nativeName: "Українська", flag: "🇺🇦", name: "Ukrainian" },
  { code: "ur", nativeName: "اردو", flag: "🇵🇰", name: "Urdu" },
  { code: "vi", nativeName: "Tiếng Việt", flag: "🇻🇳", name: "Vietnamese" },
  { code: "zu", nativeName: "Zulu", flag: "🇿🇦", name: "Zulu" },
  {
    code: "az",
    nativeName: "Azərbaycan dili",
    flag: "🇦🇿",
    name: "Azerbaijani",
  },
  { code: "cs", nativeName: "Čeština", flag: "🇨🇿", name: "Czech" },
  {
    code: "zh-HK",
    nativeName: "中文（香港）",
    name: "Chinese (Hong Kong)",
    flag: "🇭🇰",
  },
  {
    code: "zh-TW",
    nativeName: "中文（繁體）",
    name: "Chinese (Traditional)",
    flag: "🇹🇼",
  },
  {
    code: "zh",
    nativeName: "中文（简体）",
    name: "Chinese (Simplified)",
    flag: "🇨🇳",
  },
  { code: "el", nativeName: "Ελληνικά", name: "Greek", flag: "🇬🇷" },
  {
    code: "es-419",
    nativeName: "Español (Latinoamérica)",
    name: "Spanish (Latin America)",
    flag: "🌎",
  },
  {
    code: "es-US",
    nativeName: "Español (Estados Unidos)",
    name: "Spanish (United States)",
    flag: "🇺🇸",
  },
  {
    code: "es",
    nativeName: "Español (España)",
    name: "Spanish (Spain)",
    flag: "🇪🇸",
  },
  { code: "sv", nativeName: "Svenska", name: "Swedish", flag: "🇸🇪" },
];
